### ISSUE TITLE
Can this work for Godot 4+ multiplayer open-world chunk system?

### ISSUE THREAD

**Issue by WithinAmnesia** [Frejbo/Minecraft-mapart#1]
I am doing a from scratch build now for the multiplayer chunk system. What should I do for the server and the data and chunk storage?
I have a few leads and some more thoughts and resources can be found here:
https://github.com/WithinAmnesia/ARPG/discussions/16 <Start fresh thread.
https://github.com/WithinAmnesia/ARPG/discussions/15 <Previous start thread.
It was suggested I build a from scratch Multiplayer seamless chunk system that eventually be put together where it can handle 2K-16K+ players on the same server. What should be done for a web deployment to also run on a browser? I was suggested to try and do a chunk storage system similar to Minecraft or Terraria where each chunk is stored individually and accessed by the server in communication with the player clients. What should be done to solve this chunk puzzle? All feedback is welcome.

**Comment by Frejbo** [comment]
I think you are in the wrong place for this. This is an old personal project I did to try to generate minecraft maparts from images. Had a few bugs and didn't look that good.

**Comment by WithinAmnesia** [comment]
Thank you for replying. What should I find help and do you have some thoughts and suggestions or people ask?All feedback is welcome, take care.

**Comment by Frejbo** [comment]
As I'm not fully sure what you want to it's hard to give specific feedback but why not ask on Reddit?

**Comment by WithinAmnesia** [comment]
I've asked around reddit and on the github places and on discords but it's good to ask people directly too. Its good community building to seek input and have all feedback be welcome.

**Comment by Frejbo** [comment]
That's true but I'm afraid I can't help that much. I wish you luck though!

**Comment by WithinAmnesia** [comment]
That's okay. Watcha working on? Good luck to you too.
Also https://github.com/Zylann/voxelgame/issues/101#issuecomment-1958792464 + https://github.com/WithinAmnesia/ARPG/discussions/16#discussioncomment-8550378 Big 2D/3D hybrid progress update! It all works!
